version: '3.8'

services:
  # Production service
  nextjs:
    container_name: heroui-nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    # Uncomment to use environment file
    # env_file:
    #   - .env.production
    
  # Development service with hot-reload
  nextjs-dev:
    container_name: heroui-nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev
    profiles:
      - dev
    stdin_open: true
    tty: true